INSERT INTO Authorities (authorityType, username) VALUES (N'ROLE_ADMIN', N'admin');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Jiuzhai', N'China', '4741442084');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Plavsk', N'Russia', '1428070706');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Proletarskiy', N'Russia', '5121007584');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Suvorov', N'Russia', '7327912603');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Tomigusuku', N'Japan', '8545073990');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Durham', N'United States', '9191415249');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Erbil', N'Iraq', '4441179266');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Bur', N'Afghanistan', '2659755985');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Gie', N'Poland', '1347297232');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Tozeur', N'Tunisia', '7121781911');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Cliza', N'Bolivia', '7067561395');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Mekarjaya Satu', N'Indonesia', '8334270144');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Yangchun', N'China', '8535012165');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Aviúges', N'Portugal', '6025669760');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Jivia', N'Peru', '6726877920');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Moutnice', N'Czech Republic', '5563275115');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Hedong', N'China', '4869686048');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Bowen Island', N'Canada', '1562415046');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Gevgelija', N'Macedonia', '1844538347');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Gagarawa', N'Nigeria', '5024149119');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Koramlik', N'China', '4404383615');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Bologna', N'Italy', '5484459453');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Longde Chengguanzhen', N'China', '6646455031');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Hongqiao', N'China', '1643481967');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Sandia', N'Peru', '8427103197');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Cambarus', N'Philippines', '4617364745');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Xiongji', N'China', '9132399854');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Tame', N'Colombia', '5927275978');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Hayama', N'Japan', '4439957818');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Nangkapayung', N'Indonesia', '5924419163');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Issa', N'Russia', '7257232339');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Jinjiahe', N'China', '2313187274');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Thāru Shāh', N'Pakistan', '3053912246');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Anjō', N'Japan', '9274524721');
INSERT INTO BillingAddress (city, country, zipcode) VALUES (N'Nanam', N'North Korea', '7401877461');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'330 Tony Terrace', N'Dazaifu', 'Japan', '3225792042');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'388 Erie Road', N'Lianhua', 'China', '2025707328');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'20921 Rutledge Lane', N'Xijia', 'China', '5274787609');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'571 Artisan Court', N'Anwen', 'China', '1485189679');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'08 Talmadge Circle', N'Lanshan', 'China', '8215374681');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'6099 Morning Place', N'Ust-Kamenogorsk', 'Kazakhstan', '9428942239');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'1891 Manley Terrace', N'Bairros', 'Portugal', '4193030061');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'5 Hermina Plaza', N'São Lourenço da Mata', 'Brazil', '2236814794');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'52914 Darwin Crossing', N'Bergen', 'Norway', '7646703428');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'1 Transport Drive', N'Thị Trấn Tà Lùng', 'Vietnam', '3895805218');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'48022 Blaine Alley', N'Jiyukou', 'China', '4861808930');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'3299 Brickson Park Court', N'Tanniu', 'China', '4414301115');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'85834 2nd Alley', N'Guohuan', 'China', '8936691349');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'4 Novick Junction', N'Huibu', 'China', '4814762735');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'87540 Sugar Drive', N'Ankou', 'China', '7165211561');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'152 Wayridge Drive', N'Namioka', 'Japan', '7828259699');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'27594 Jackson Court', N'Renhe', 'China', '5587636982');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'7 Mifflin Point', N'Tsementnozavodskiy', 'Russia', '3502036303');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'743 New Castle Point', N'Lianhe', 'China', '2455889727');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'683 Ridge Oak Crossing', N'Novomoskovs’k', 'Ukraine', '8072578642');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'7 Ridgeview Way', N'Biała', 'Poland', '2737502133');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'9 Blackbird Street', N'Mainri', 'China', '2053318728');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'11 Barby Court', N'Tuba', 'China', '8212045706');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'169 Sloan Junction', N'Slatyne', 'Ukraine', '2898477959');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'00 Prairieview Center', N'Piława Górna', 'Poland', '6786548035');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'5847 Norway Maple Trail', N'Sukamaju', 'Indonesia', '7854733615');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'942 Northfield Trail', N'Sakassou', 'Ivory Coast', '6823442871');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'66 Crescent Oaks Center', N'La Paz', 'Uruguay', '3011419557');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'7 Golf Course Way', N'Steinkjer', 'Norway', '5467344273');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'71 Raven Crossing', N'Sobral da Abelheira', 'Portugal', '2463029856');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'10408 Meadow Valley Street', N'Krzykosy', 'Poland', '6393599146');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'67005 Brickson Park Circle', N'Milicz', 'Poland', '4802379121');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'584 Union Street', N'Speightstown', 'Barbados', '1863432597');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'03 Sullivan Park', N'Banyo', 'Cameroon', '8405043352');
INSERT INTO ShippingAddress (address, city, country, zipcode) VALUES (N'99916 Starling Point', N'Kirovsk', 'Russia', '7665366516');
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('rsidgwick0@hell.com', 'Rafaello Sidgwick', '9519631726', 1, 123, 'admin', null, null, null);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('ljaksic1@archive.org', 'Loria Jaksic', '4303753890', 1, 123, 'alpha', 16, null, 6);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('erylands2@domainmarket.com', 'Eimile Rylands', '8066828767', 0, 123, 'erylands2', 2, null, 16);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('kskellorne3@icq.com', 'Karie Skellorne', '5677689578', 1, 123, 'kskellorne3', 32, null, 1);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('sshimmans4@is.gd', 'Shandy Shimmans', '5796619397', 0, 123, 'sshimmans4', 23, null, 29);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('rtwiggins5@nationalgeographic.com', 'Rogerio Twiggins', '9565602399', 1, 123, 'rtwiggins5', 33, null, 32);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('bjoao6@smh.com.au', 'Blythe Joao', '7018223940', 0, 123, 'bjoao6', 15, null, 7);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('rhebdon7@chicagotribune.com', 'Reidar Hebdon', '3182773059', 1, 123, 'rhebdon7', 4, null, 1);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('tgrzeszczyk8@free.fr', 'Trisha Grzeszczyk', '1151258312', 1, 123, 'tgrzeszczyk8', 30, null, 24);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('gburnall9@salon.com', 'Giustino Burnall', '3037193750', 1, 123, 'gburnall9', 24, null, 19);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('anoea@guardian.co.uk', 'Ase Noe', '5608049125', 0, 123, 'anoea', 4, null, 19);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('cfaithfullb@goo.ne.jp', 'Caren Faithfull', '5019895087', 1, 123, 'cfaithfullb', 34, null, 13);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('iwillartonc@flickr.com', 'Ike Willarton', '4471880241', 1, 123, 'iwillartonc', 29, null, 16);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('fzylbermannd@google.de', 'Filippa Zylbermann', '8717931545', 1, 123, 'fzylbermannd', 13, null, 27);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('tgonneaue@desdev.cn', 'Terri Gonneau', '9802574311', 0, 123, 'tgonneaue', 17, null, 18);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('mboerderf@yellowpages.com', 'Marty Boerder', '8807203102', 1, 123, 'mboerderf', 35, null, 6);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('cweskerg@netscape.com', 'Constantino Wesker', '7137786299', 1, 123, 'cweskerg', 14, null, 16);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('vcoenh@wunderground.com', 'Veronica Coen', '6074456228', 1, 123, 'vcoenh', 17, null, 13);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('edibolli@usgs.gov', 'Elisha Diboll', '4023259505', 1, 123, 'edibolli', 28, null, 6);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('vclemenzoj@squidoo.com', 'Vanya Clemenzo', '2312639596', 1, 123, 'vclemenzoj', 33, null, 29);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('bpavlovk@simplemachines.org', 'Beltran Pavlov', '5177849161', 1, 123, 'bpavlovk', 19, null, 30);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('mchiccol@earthlink.net', 'Morlee Chicco', '4892441416', 1, 123, 'mchiccol', 2, null, 13);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('gfinckenm@ftc.gov', 'Ganny Fincken', '1562205264', 1, 123, 'gfinckenm', 34, null, 34);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('vdyken@behance.net', 'Vin Dyke', '7725997925', 1, 123, 'vdyken', 20, null, 17);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('glowsono@yelp.com', 'Garland Lowson', '6428814336', 1, 123, 'glowsono', 30, null, 11);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('pspadottop@patch.com', 'Padget Spadotto', '4835323825', 1, 123, 'pspadottop', 6, null, 32);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('mrilingsq@github.io', 'Marji Rilings', '8209345609', 1, 123, 'mrilingsq', 22, null, 19);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('ltwelftreer@bloomberg.com', 'Lemuel Twelftree', '9163918849', 1, 123, 'ltwelftreer', 14, null, 1);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('cbaylesss@xrea.com', 'Clementius Bayless', '3653904827', 1, 123, 'cbaylesss', 2, null, 5);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('amitchleyt@cbsnews.com', 'Agnes Mitchley', '9856686081', 1, 123, 'amitchleyt', 27, null, 26);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('nmorettou@nationalgeographic.com', 'Norry Moretto', '2274348344', 1, 123, 'nmorettou', 25, null, 11);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('bdoorlyv@microsoft.com', 'Bibi Doorly', '5336025865', 1, 123, 'bdoorlyv', 30, null, 19);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('idagnanw@netvibes.com', 'Ingrim Dagnan', '9943208802', 1, 123, 'idagnanw', 7, null, 17);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('amolnarx@springer.com', 'Allie Molnar', '5173131952', 1, 123, 'amolnarx', 4, null, 8);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('mlomeny@cnn.com', 'Mabelle Lomen', '1663630252', 1, 123, 'mlomeny', 24, null, 2);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('olez@about.me', 'Onida Le Pine', '8771965010', 1, 123, 'olez', 16, null, 20);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('nmeo10@homestead.com', 'Nikolaus Meo', '6783674102', 1, 123, 'nmeo10', 4, null, 19);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('mbickerton11@topsy.com', 'Merrie Bickerton', '2734722979', 1, 123, 'mbickerton11', 2, null, 34);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('ndallosso12@gmpg.org', 'Newton Dallosso', '6825956301', 1, 123, 'ndallosso12', 25, null, 5);
INSERT INTO Customer (customerEmailAddress, customerName, customerPhoneNumber, enabled, password, username, billingAddressId, cartId, shippingAddressId) VALUES ('bjurasz13@people.com.cn', 'Bil Jurasz', '1813390999', 1, 123, 'bjurasz13', 1, null, 21);
INSERT INTO Message (message, name, sentTime, email, customerId) VALUES (N'When will Lebron shoes arrive?', N'Joe Biden', '2021-12-1 05:51:01.830', 'cfaithfullb@goo.ne.jp', 12);
INSERT INTO Message (message, name, sentTime, email, customerId) VALUES (N'Do you have jackets in XXXL?', N'John Wick', '2021-12-9 04:59:01.830', 'n18dccn214@student.ptithcm.edu.vn', 21);
INSERT INTO Message (message, name, sentTime, email, customerId) VALUES (N'Jordan 7 arrive yet?', N'Jack Jack', '2021-12-12 18:59:01.830' , 'skywalker2834@gmail.com', 14);
INSERT INTO Message (message, name, sentTime, email, customerId) VALUES (N'Devolved tertiary superstructure!', N'Johny Cash', '2021-12-13 12:59:01.830', 'kdittson3@deliciousdays.com', null);
INSERT INTO Message (message, name, sentTime, email, customerId) VALUES (N'Object-based coherent project?', N'Joey J', '2021-12-11 01:29:01.830', 'ckellar4@msn.com', null);
